Exploratory data analysis
Here we under the dataset how it is actually present after that which table is useful to create aggregated table which will be used for further analysis.
1) Vendor selection profitability
2) Product pricing profitiability

In [1]:
import pandas as pd
import sqlite3

In [2]:
conn=sqlite3.connect('C:\\Vendor project\\data1.db') # creating a connection to the database

In [3]:
#checking the tables in the database
tables=pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table';", conn)
tables

                   name
0       begin_inventory
1         end_inventory
2             purchases
3       purchase_prices
4                 sales
5        vendor_invoice
6       purchase_agg_df
7  Vendor_sales_summary

In [4]:
for table in tables['name']:
    print( '-'*50,f'{table}','-'*50)
    print('count of records:',pd.read_sql(f'SELECT COUNT(*) as count FROM {table}', conn)['count'].values[0])
    display(pd.read_sql(f'SELECT * FROM {table} LIMIT 5', conn))

-------------------------------------------------- begin_inventory --------------------------------------------------
count of records: 206529

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,2024-01-01
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,2024-01-01
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,2024-01-01
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,2024-01-01
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.99,2024-01-01

-------------------------------------------------- end_inventory --------------------------------------------------
count of records: 224489

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,12.99,2024-12-31
1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,36.99,2024-12-31
2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,38.99,2024-12-31
3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,34.99,2024-12-31
4,1_HARDERSFIELD_75,1,HARDERSFIELD,75,Three Olives Tomato Vodka,750mL,7,14.99,2024-12-31

-------------------------------------------------- purchases --------------------------------------------------
count of records: 2372474

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1

-------------------------------------------------- purchase_prices --------------------------------------------------
count of records: 12261

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

-------------------------------------------------- sales --------------------------------------------------
count of records: 12825363

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-01,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,2024-01-02,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-03,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,2024-01-08,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,2024-01-09,375.0,1,0.79,12546,JIM BEAM BRANDS COMPANY

-------------------------------------------------- vendor_invoice --------------------------------------------------
count of records: 5543

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,None
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,None

-------------------------------------------------- purchase_agg_df --------------------------------------------------
count of records: 5543

,PONumber,total_brands,total_item_quantity,total_item_dollars,avg_receiving_delay
0,8106,81,10100,137483.78,12.614130
1,8107,2,24,348.72,12.500000
2,8108,165,8466,60281.13,12.632479
3,8109,23,2246,14298.09,12.626866
4,8110,183,8086,56493.23,12.695271

-------------------------------------------------- Vendor_sales_summary --------------------------------------------------
count of records: 10692

,VendorNumber,VendorName,Brand,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,Description,freight_cost,GrossProfit,ProfitMargin,StockTurnover,SalesToPurchaseRatio
0,1128,BROWN-FORMAN CORP,1233,26.27,36.99,1750.0,145080,3811251.60,142049.0,5101919.51,672819.31,260999.20,Jack Daniels No 7 Black,68601.68,1290667.91,25.297693,0.979108,1.338647
1,4425,MARTIGNETTI COMPANIES,3405,23.19,28.99,1750.0,164038,3804041.22,160247.0,4819073.49,561512.37,294438.66,Tito's Handmade Vodka,144929.24,1015032.27,21.062810,0.976890,1.266830
2,17035,PERNOD RICARD USA,8068,18.24,24.99,1750.0,187407,3418303.68,187140.0,4538120.60,461140.15,343854.07,Absolut 80 Proof,123780.22,1119816.92,24.675786,0.998575,1.327594
3,3960,DIAGEO NORTH AMERICA INC,4261,16.17,22.99,1750.0,201682,3261197.94,200412.0,4475972.88,420050.01,368242.80,Capt Morgan Spiced Rum,257032.07,1214774.94,27.139908,0.993703,1.372493
4,3960,DIAGEO NORTH AMERICA INC,3545,21.89,29.99,1750.0,138109,3023206.01,135838.0,4223107.62,545778.28,249587.83,Ketel One Vodka,257032.07,1199901.61,28.412764,0.983556,1.396897

As we have the data ingested into the database after that we see the how many records present in each table by the count function through for loop , after going through each table we come to know:
1) purchase table has actual purchase data such as date of purchase,products purchased by vendors,amount paid and purchased quantity
2) Purchase_price table has the product wise actual and purchased prices.Here we got unique column as vendor number and brand.
3)vendor_invoice has similar data of purchase table having additional column for freight. It has unique column vendor and PO number.
4)Sales table has actual sales transcations,brand purchased by vendors,the quantity sold,the selling price,the revenue earned.

To make analysis we need to create a summary table containing:

1)Purchase transcations made by vendor
2)sales transcation data
3)freight costs for each vendor
4)actual product prices from vendors

In [5]:
# From vendor table we are taking the column frieght to make further analysis
freight_data=pd.read_sql('SELECT VendorNumber,sum(Freight) as freight_cost FROM vendor_invoice GROUP BY VendorNumber', conn)

In [9]:
freight_data['Cumulative Freight Cost']=freight_data['freight_cost'].cumsum()
freight_data=freight_data.sort_values(by='freight_cost', ascending=False)
freight_data

     VendorNumber  freight_cost  Cumulative Freight Cost
40           3960     257032.07                257032.07
42           4425     144929.24                401961.31
95          12546     123880.97                525842.28
99          17035     123780.22                649622.50
7             480      89286.27                738908.77
..            ...           ...                      ...
110         90033          0.61               1640473.49
1              54          0.48               1640473.97
107         90026          0.36               1640474.33
17           1439          0.27               1640474.60
125        201359          0.09               1640474.69

[126 rows x 3 columns]

In [20]:
pd.read_sql_query("""select p.VendorNumber,p.VendorName,p.Brand,p.PurchasePrice,pp.Volume,pp.Price as actual_price,sum(p.Quantity) as totalPurchasequantity,
                  Sum(p.Dollars) as Totalpurchasedollars from purchases p JOIN 
                   purchase_prices pp ON p.Brand=pp.Brand where p.PurchasePrice>0
                   group by p.VendorNumber,p.VendorName,p.Brand order by Totalpurchasedollars""",conn)

#Here we join the purchase and Purchase_price table to get the actual price of the product and then we are calculating the total purchase quantity and dollars for each vendor and brand. This will help us to identify

,VendorNumber,VendorName,Brand,PurchasePrice,Volume,actual_price,totalPurchasequantity,Totalpurchasedollars
0,7245,PROXIMO SPIRITS INC.,3065,0.71,50,0.99,1,0.71
1,3960,DIAGEO NORTH AMERICA INC,6127,1.47,200,1.99,1,1.47
2,3924,HEAVEN HILL DISTILLERIES,9123,0.74,50,0.99,2,1.48
3,8004,SAZERAC CO INC,5683,0.39,50,0.49,6,2.34
4,9815,WINE GROUP INC,8527,1.32,750,4.99,2,2.64
...,...,...,...,...,...,...,...,...
10687,3960,DIAGEO NORTH AMERICA INC,3545,21.89,1750,29.99,138109,3023206.01
10688,3960,DIAGEO NORTH AMERICA INC,4261,16.17,1750,22.99,201682,3261197.94
10689,17035,PERNOD RICARD USA,8068,18.24,1750,24.99,187407,3418303.68
10690,4425,MARTIGNETTI COMPANIES,3405,23.19,1750,28.99,164038,3804041.22
10691,1128,BROWN-FORMAN CORP,1233,26.27,1750,36.99,145080,3811251.60

In [21]:
pd.read_sql_query( """Select VendorNo,Brand,Sum(SalesDollars) as TotalSalesDollars,
                  Sum(SalesPrice) as TotalSalesPrice,
                  Sum(SalesQuantity) as TotalSalesQuantity,
                  Sum(ExciseTax) as TotalExciseTax
                  from sales group by VendorNo,Brand  order by TotalSalesDollars """,conn)

,VendorNo,Brand,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax
0,8004,5287,0.98,0.98,2,0.10
1,9206,2773,0.99,0.99,1,0.05
2,3252,3933,1.98,0.99,2,0.10
3,3924,9123,1.98,0.99,2,0.10
4,10050,3623,1.98,1.98,2,0.10
...,...,...,...,...,...,...
11267,3960,3545,4223107.62,545778.28,135838,249587.83
11268,3960,4261,4475972.88,420050.01,200412,368242.80
11269,17035,8068,4538120.60,461140.15,187140,343854.07
11270,4425,3405,4819073.49,561512.37,160247,294438.66
11271,1128,1233,5101919.51,672819.31,142049,260999.20

Now we are going to make Vendor_sales_summary table which as data of freight table which we previously made along with table as purchase summary and sales summary so after that we joined the tables by it's uniqueness vendor number and brand.

In [ ]:

Vendor_sales_summary = pd.read_sql_query("""
    WITH freight_data AS (
        SELECT VendorNumber, SUM(Freight) AS freight_cost
        FROM vendor_invoice
        GROUP BY VendorNumber
    ),
    PurchaseSummary AS (
        SELECT 
            p.VendorNumber, p.VendorName, p.Brand,
            p.PurchasePrice, pp.Volume,
            pp.Price AS actual_price,
            SUM(p.Quantity) AS TotalPurchaseQuantity,
            SUM(p.Dollars)  AS TotalPurchaseDollars
        FROM purchases p
        JOIN purchase_prices pp ON p.Brand = pp.Brand
        WHERE p.PurchasePrice > 0
        GROUP BY p.VendorNumber, p.VendorName, p.Brand
    ),
    SalesSummary AS (
        SELECT 
            VendorNo, Brand,
            Description,
            SUM(SalesDollars)  AS TotalSalesDollars,
            SUM(SalesPrice)    AS TotalSalesPrice,
            SUM(SalesQuantity) AS TotalSalesQuantity,
            SUM(ExciseTax)     AS TotalExciseTax
        FROM sales
        GROUP BY VendorNo, Brand, Description
    )
    SELECT
        ps.VendorNumber, ps.VendorName, ps.Brand,
        ps.PurchasePrice, ps.actual_price AS ActualPrice,
        ps.Volume, ps.TotalPurchaseQuantity, ps.TotalPurchaseDollars,
        ss.TotalSalesQuantity, ss.TotalSalesDollars,
        ss.TotalSalesPrice, ss.TotalExciseTax,
        ss.Description,
        fd.freight_cost
    FROM PurchaseSummary ps
    LEFT JOIN SalesSummary ss 
           ON ps.VendorNumber = ss.VendorNo AND ps.Brand = ss.Brand
    LEFT JOIN freight_data fd 
           ON ps.VendorNumber = fd.VendorNumber
    ORDER BY ps.TotalPurchaseDollars DESC
""", conn)

print("DataFrame created:", Vendor_sales_summary.shape)
print(Vendor_sales_summary.columns.tolist())

In [23]:
Vendor_sales_summary

,VendorNumber,VendorName,Brand,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,Description,freight_cost
0,1128,BROWN-FORMAN CORP,1233,26.27,36.99,1750,145080,3811251.60,142049.0,5101919.51,672819.31,260999.20,Jack Daniels No 7 Black,68601.68
1,4425,MARTIGNETTI COMPANIES,3405,23.19,28.99,1750,164038,3804041.22,160247.0,4819073.49,561512.37,294438.66,Tito's Handmade Vodka,144929.24
2,17035,PERNOD RICARD USA,8068,18.24,24.99,1750,187407,3418303.68,187140.0,4538120.60,461140.15,343854.07,Absolut 80 Proof,123780.22
3,3960,DIAGEO NORTH AMERICA INC,4261,16.17,22.99,1750,201682,3261197.94,200412.0,4475972.88,420050.01,368242.80,Capt Morgan Spiced Rum,257032.07
4,3960,DIAGEO NORTH AMERICA INC,3545,21.89,29.99,1750,138109,3023206.01,135838.0,4223107.62,545778.28,249587.83,Ketel One Vodka,257032.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,9815,WINE GROUP INC,8527,1.32,4.99,750,2,2.64,5.0,15.95,10.96,0.55,Concannon Glen Ellen Wh Zin,27100.41
10688,8004,SAZERAC CO INC,5683,0.39,0.49,50,6,2.34,134.0,65.66,1.47,7.04,Dr McGillicuddy's Apple Pie,50293.62
10689,3924,HEAVEN HILL DISTILLERIES,9123,0.74,0.99,50,2,1.48,2.0,1.98,0.99,0.10,Deep Eddy Vodka,14069.87
10690,3960,DIAGEO NORTH AMERICA INC,6127,1.47,1.99,200,1,1.47,72.0,143.28,77.61,15.12,The Club Strawbry Margarita,257032.07
10691,7245,PROXIMO SPIRITS INC.,3065,0.71,0.99,50,1,0.71,86.0,85.14,33.66,4.46,Three Olives Grape Vodka,38994.78

In [24]:
Vendor_sales_summary.dtypes

VendorNumber               int64
VendorName                object
Brand                      int64
PurchasePrice            float64
ActualPrice              float64
Volume                    object
TotalPurchaseQuantity      int64
TotalPurchaseDollars     float64
TotalSalesQuantity       float64
TotalSalesDollars        float64
TotalSalesPrice          float64
TotalExciseTax           float64
Description               object
freight_cost             float64
dtype: object

Now we got the final table name as vendor_sales_summary on which we are going to be make analysis so before moving towards it, we need to make ensure that data inside  is in clean form for that we use fuctions like unique(),fillna(),str.strip() etc . In data cleaning process we erase null and duplicate values, convert into columns into appropriate datatypes, replace the particular data , remove spaces from string datatypes.

In [25]:
Vendor_sales_summary.isnull().sum()

VendorNumber               0
VendorName                 0
Brand                      0
PurchasePrice              0
ActualPrice                0
Volume                     0
TotalPurchaseQuantity      0
TotalPurchaseDollars       0
TotalSalesQuantity       178
TotalSalesDollars        178
TotalSalesPrice          178
TotalExciseTax           178
Description              178
freight_cost               0
dtype: int64

In [26]:
Vendor_sales_summary['Volume']=Vendor_sales_summary['Volume'].astype('float64')

In [27]:
Vendor_sales_summary.fillna(0,inplace=True)

In [28]:
Vendor_sales_summary['VendorName']=Vendor_sales_summary['VendorName'].str.strip()

In [29]:
Vendor_sales_summary['Description']=Vendor_sales_summary['Description'].str.strip()

In [ ]:
Vendor_sales_summary['VendorName'].unique()

In [31]:
Vendor_sales_summary['Description'].unique()

array(['Jack Daniels No 7 Black', "Tito's Handmade Vodka",
       'Absolut 80 Proof', ..., 'Crown Royal Apple',
       'Concannon Glen Ellen Wh Zin', 'The Club Strawbry Margarita'],
      shape=(9484,), dtype=object)

In [32]:
Vendor_sales_summary.isnull().sum()

VendorNumber               0
VendorName                 0
Brand                      0
PurchasePrice              0
ActualPrice                0
Volume                     0
TotalPurchaseQuantity      0
TotalPurchaseDollars       0
TotalSalesQuantity         0
TotalSalesDollars          0
TotalSalesPrice            0
TotalExciseTax             0
Description              178
freight_cost               0
dtype: int64

We also need to add columns inside the table which will become useful for further analysis such gross profit,profit margin,stockturnover and sales to purchase ratio.

In [33]:
Vendor_sales_summary['GrossProfit']=Vendor_sales_summary['TotalSalesDollars']-Vendor_sales_summary['TotalPurchaseDollars']

In [34]:
Vendor_sales_summary['ProfitMargin']=Vendor_sales_summary['GrossProfit']/Vendor_sales_summary['TotalSalesDollars']*100

In [35]:
Vendor_sales_summary['StockTurnover']=Vendor_sales_summary['TotalSalesQuantity']/Vendor_sales_summary['TotalPurchaseQuantity']

In [36]:
Vendor_sales_summary['SalesToPurchaseRatio']=Vendor_sales_summary['TotalSalesDollars']/Vendor_sales_summary['TotalPurchaseDollars']

In [37]:
Vendor_sales_summary.columns

Index(['VendorNumber', 'VendorName', 'Brand', 'PurchasePrice', 'ActualPrice',
       'Volume', 'TotalPurchaseQuantity', 'TotalPurchaseDollars',
       'TotalSalesQuantity', 'TotalSalesDollars', 'TotalSalesPrice',
       'TotalExciseTax', 'Description', 'freight_cost', 'GrossProfit',
       'ProfitMargin', 'StockTurnover', 'SalesToPurchaseRatio'],
      dtype='object')

In [38]:

#just to save DataFrame to DB
Vendor_sales_summary.to_sql(
    'Vendor_sales_summary',
    conn,
    if_exists='replace',   # replaces if already exists
    index=False
)
conn.commit()
print("Saved successfully!")
print(Vendor_sales_summary.shape)

Saved successfully!
(10692, 18)

In [39]:
Vendor_sales_summary.head()

,VendorNumber,VendorName,Brand,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,Description,freight_cost,GrossProfit,ProfitMargin,StockTurnover,SalesToPurchaseRatio
0,1128,BROWN-FORMAN CORP,1233,26.27,36.99,1750.0,145080,3811251.60,142049.0,5101919.51,672819.31,260999.20,Jack Daniels No 7 Black,68601.68,1290667.91,25.297693,0.979108,1.338647
1,4425,MARTIGNETTI COMPANIES,3405,23.19,28.99,1750.0,164038,3804041.22,160247.0,4819073.49,561512.37,294438.66,Tito's Handmade Vodka,144929.24,1015032.27,21.062810,0.976890,1.266830
2,17035,PERNOD RICARD USA,8068,18.24,24.99,1750.0,187407,3418303.68,187140.0,4538120.60,461140.15,343854.07,Absolut 80 Proof,123780.22,1119816.92,24.675786,0.998575,1.327594
3,3960,DIAGEO NORTH AMERICA INC,4261,16.17,22.99,1750.0,201682,3261197.94,200412.0,4475972.88,420050.01,368242.80,Capt Morgan Spiced Rum,257032.07,1214774.94,27.139908,0.993703,1.372493
4,3960,DIAGEO NORTH AMERICA INC,3545,21.89,29.99,1750.0,138109,3023206.01,135838.0,4223107.62,545778.28,249587.83,Ketel One Vodka,257032.07,1199901.61,28.412764,0.983556,1.396897

In [40]:
Vendor_sales_summary.to_csv('Vendor_sales_summary.csv', index=False)
print(" CSV file saved as 'Vendor_sales_summary.csv'")

 CSV file saved as 'Vendor_sales_summary.csv'